name: React-Redux CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-folder: 'dist'

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      # Here, you can add any other steps you need for your Jekyll site build, 
      # such as setting up Ruby and Jekyll, building the site, etc.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: ${{ needs.build.outputs.build-folder }}  # The folder the action should deploy, from the output of the build job.
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication.
